### ISSUE TITLE
Link for download on website is broken

### ISSUE THREAD

**Issue by emanuelstanciu** [opensemanticsearch/open-semantic-search-appliance#3]
Title says it all

**Comment by opensemanticsearch** [comment]
Since old version of the Server VM had very old search engine version, i deleted it.

New version available next week, when the build process of appliance VM is fully automated, too (like for the Debian packages, which are available for the newest version on same day after code release).

**Comment by emanuelstanciu** [comment]
Great stuff, thanks, I'll wait patiently then. Can you please update this issue and close once it's available so I'll receive a notification. Thanks

**Comment by dacracot** [comment]
Still waiting, albeit a little less patiently.

**Comment by guebert** [comment]
Hm, "next week" seems to be over ... ;-)
Anything new regarding this issue?

Michael

**Comment by opensemanticsearch** [comment]
Because of ending year and some rest budgets for 2016 had to priorize some work for paying customers, mostly using the Linux packages or desktop search VM. If no additional projects so i can do all planed work full next week i hope for new open source releases untill Friday 9.12.

**Comment by guebert** [comment]
Thanks for this information!

BTW - any plans / changes to get an virtual appliance fitting for Hyper-V, at least a "General virtual appliance in the OVF format with no vendor specific tools." like http://www.searchdaimon.com/download/. I think, OSS will fit our requirements and have a Windows 2012 Server running, hosting the file server (w2k12, too) in Hyper-V. For the "shared folders", which are not available in Hyper-V, there should be a simple config tool / file.

Many thanks

Michael

**Comment by guebert** [comment]
Are we talking about the same thing?

"Next week" is not 2017, IMHO.

Website says "Not available at the moment. New upgraded VM will be available in october 2017:"

????

**Comment by opensemanticsearch** [comment]
Next year 2017 was a mistake. Meant this year 2016. So because of unplaned payed projects end of the year this features/builds will be ready in december (this month), not october.

**Comment by Mandalka** [comment]
Build scripts and configs are upgraded with newest Open Semantic Search version and builds/upload running, the virtual machine image should be available online while the weekend.

**Comment by Mandalka** [comment]
Plans for another virtualization solutions than Virtual Box:

The new VM doesn't need Virtual Box shared folder for index anymore, so it should be runnable on other virtualization platforms, too.

I copied that part from some last work on Desktop Search VM where an internal index was configured by default for easier installation some time ago.

But if not using Virtual Box shared folders for mounting the folder(s) with documents, you have to mount your file systems yourself by standard Linux tools / configs of the installed Debian Linux.

If no payed project for that, i won't do further works for other virtualization solutions than the in Desktop Search used Virtual Box and maybe Docker (if we switch the search servers from Virtual Box to Docker in an institution i work for next year).

If you don't want to use standard mount configs/tools, maybe there is a open source UI for mounting file systems and shares to Debian system, since there are many command line tools for mounting different (virtual) file systems. For example search for [FUSE](https://en.wikipedia.org/wiki/Filesystem_in_Userspace) ...

**Comment by opensemanticsearch** [comment]
Build & upload is done. New version of Open Semantic Search Appliance is available for download.
