### ISSUE TITLE
How (where) to mount external data volumes to (which) internal path?

### ISSUE THREAD

**Issue by guebert** [opensemanticsearch/open-semantic-search-appliance#5]
Mandalka wrote (https://github.com/opensemanticsearch/open-semantic-search-appliance/issues/3)

> But if not using Virtual Box shared folders for mounting the folder(s) with documents, you have to mount your file systems yourself by standard Linux tools / configs of the installed Debian Linux.

Can anybody tell me, to which internal path data and index volumes have to been mapped?

eg \\server\volume\data-folder --> \data (???) 
or --> \mnt\data
or --> \home\.... 

Maybe somebody could post an example of a config file for that (fstab) like this:

> //192.168.1.100/volume/data-folder /mnt/data cifs username=otto,passwd=geheim,domain=Gruppe1,[ro|rw] 0 0
> 
> [ro|rw] = read-only or read-write

Many thanks!

Michael

**Comment by opensemanticsearch** [comment]
You can mount it to a path you want. So its not a search engine issue but a standard Linux mount issue.

A mapping in the search config is not necessary.

The mapping config is available for the case the links should point to other paths because your clients have use other mount points than your search server.

For example if you use the automount from Virtual box, where the path will be changed to /media/sf_ prefix.

If you want map some paths just use /etc/etl/connector-files and the option
config['mappings'] ...

You can use more than one mapping by comma seperated mappings like

config['mappings'] = {
"/media/sf_one": "file:///one",
"/mount/two": "file:///two",
}
