### ISSUE TITLE
Any experience running under MS Hyper-V (Server 2012 od 

### ISSUE THREAD

**Issue by guebert** [opensemanticsearch/open-semantic-search-appliance#6]

**Comment by guebert** [comment]
Hallo!

I would like to run OSS on my win2012 server. This server has a file-server-vm running and I would like to "add" oss vm. My technician converted the ova-file to vhd/vhdx file. We could start oss, but the performance is worse than in virual box and - more important - oss crashes very often. We we run it unter virtual box, there's no problem, but I do not want to install hyper-v and virtual box in parallel on my server ...

Is there any experience of running oss under hyper-v? Anything special to be aware of?

Michael

**Comment by Mandalka** [comment]
I have no experience with other virtualization environments than Virtual Box, VMWare or KVM but you should be aware of that the downloadable VM has installed kernel modules for virtualization with Virtual Box (virtual box guest utilities), which make it running more performant and might not work in other virtualization environments very well.

Maybe there are similar kernel modules or extensions for the Debian base of the VM supporting your special virtualization environment.

Maybe crashes are because of very special data sizes and can be optimized/customized by special settings. Not sure what kind of crashes you mean.

**Comment by guebert** [comment]
Closed, because no interest in providing an appliance for hyper-v? :-(

Michael
